[tool.ruff]
# Only lint notebooks (and optionally your Python code)
include = ["notebooks/**/*.ipynb"]
line-length = 120
fix = true

[tool.ruff.lint]
extend-select = ["I", "F" ,"E"] # Sort imports (like isort) and remove unused ones
